set(PROJECT_VERSION_MAJOR 0)
set(PROJECT_VERSION_MINOR 0)
set(PROJECT_VERSION_PATCH 0)
set(PROJECT_VERSION_STRING v0.0.0)

find_package(Git)

if(GIT_FOUND)
execute_process(
    COMMAND ${GIT_EXECUTABLE} describe --tags HEAD
    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
    OUTPUT_VARIABLE PROJECT_VERSION_STRING
    OUTPUT_STRIP_TRAILING_WHITESPACE
)

if(${PROJECT_VERSION_STRING} MATCHES "^v[0-9]+\\.[0-9]+\\.[0-9]+.*$")
    string(REGEX REPLACE "^v?([0-9]+).*" "\\1" PROJECT_VERSION_MAJOR "${PROJECT_VERSION_STRING}")
    string(REGEX REPLACE "^v?[0-9]+\\.([0-9]+).*" "\\1" PROJECT_VERSION_MINOR "${PROJECT_VERSION_STRING}")
    string(REGEX REPLACE "^v?[0-9]+\\.[0-9]+\\.([0-9]+).*" "\\1" PROJECT_VERSION_PATCH "${PROJECT_VERSION_STRING}")
endif()
endif()